spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notes_app?useSSL=false
    username: root
    password: root
#proprieta' jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect